apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: docker-spring-boot
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: docker-spring-boot
    spec:
      containers:
        - name: docker-spring-boot
          image: 'gcr.io/favorable-iris-266409/docker-spring-boot:v1'
          ports:
            - containerPort: 8095
